# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aaron McDonald
email: aaronmcdonald7@hotmail.co.uk
description: > # this means to ignore newlines until "baseurl:"
  An adaptable graduate seeking an IT position that will challenge the communication and technical skills developed at university 
  and employment. Experience in using an array of different programming languages, software tools and packages. Able to manage time 
  efficiently and meet deadlines. Works well a part of a team and unsupervised using initiative.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aaronmcdonald.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  DrSayus

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
